### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by fgprodigal** [ls-/oUF_FloatingCombatFeedback#1]
SetTextHeight makes the text so ugly, why not using SetFont to adjust the font size directly?

**Comment by ls-** [comment]
As of Legion fonts scale via `SetTextHeight` quite well, but only if `FontObject`'s height is quite... high 😐
That why there's this note in plugin's description:

> Note: If you create your own font object, I strongly recommend to use big font sizes, e.g. CombatTextFont's size is 64px.

By default plugin uses `CombatTextFont`, which is created from [SystemFont_World](https://github.com/Gethe/wow-ui-source/blob/live/SharedXML/SharedFonts.xml#L748-L799) family. With those flags it scales w/o any issues.

Or are we talking about squarish pixel fonts O_o I used `SetFont` originally in v1, but, tbh, I never liked that approach...

**Comment by fgprodigal** [comment]
Okey, I see. Thank you very much!

**Comment by ls-** [comment]
On a side note, you're using my toast's code and textures, but you haven't included ls: toasts license anywhere, not cool...

Anyways, I have a question, why did you decide to tear the addon apart, instead of adding it to your pack and simply reskinning toasts, I've provided a way to do so 🤔

**Comment by fgprodigal** [comment]
I'v added your github url inside the file, I'll add your license soon

**Comment by ls-** [comment]
I'm still curious about not adding it as an addon... Asking cuz I'm gathering feedback, haha, nothing personal.

I'm talking about [this thingy](https://github.com/ls-/ls_Toasts#how-to-reskin), is there something else you'd like to see added? o_O An option to override addon's config?

**Comment by fgprodigal** [comment]
Your addon is nearly perfect, none should be added to me now. I just wanna make my addon more ‘tidy’, no other reason. I can move it out if you mind this.

sorry for my poor English.

**Comment by ls-** [comment]
Ah, okay. 

Have a nice day, closing this issue, but if you have any questions and/or suggestions, feel free to ask.

P.S. 你的英文比我的中文要好orz
